# Generated by Django 4.0.1 on 2023-07-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_faaliyet_tag_product_faaliyet_product_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faaliyet',
            name='image',
        ),
    ]
