# Generated by Django 4.2.3 on 2023-07-24 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_faaliyet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.category'),
        ),
        migrations.AddField(
            model_name='services',
            name='is_home',
            field=models.BooleanField(null=True, verbose_name='Ana Sayfada Gösterilsin Mi?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='faaliyet',
            field=models.ManyToManyField(blank=True, to='services.faaliyet'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, to='services.tag'),
        ),
    ]
