# Generated by Django 4.2.3 on 2023-07-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_services_is_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='services',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
