# Generated by Django 4.2.3 on 2023-07-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_product_date_alter_services_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
