# Generated by Django 4.2.3 on 2023-07-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_product_date_alter_services_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_home',
            field=models.BooleanField(default=1, verbose_name='Ürün Ana Sayfada Gösterilsin Mi?'),
            preserve_default=False,
        ),
    ]
